language: cpp
compiler:
  #- clang
  - gcc
before_install:
  # Print working directory
  - pwd
  # Check CMake version.
  - cmake --version
  # Remove the rabbitmq source file since it currently times out and 
  # we don't need it.
  - sudo apt-get update -qq
  # Install Qt5
  - sudo apt-get install -qq qt-sdk
  # Fake X server
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - cmake CMakeLists.txt
  - make
  - ./run.sh